# Generated by Django 2.2.5 on 2019-09-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0002_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='clave',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='usuario',
            field=models.CharField(max_length=100),
        ),
    ]
