# Generated by Django 2.2.5 on 2019-09-11 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0003_auto_20190911_1517'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usuarios',
            new_name='usuario',
        ),
    ]
